### ISSUE TITLE
Recommendation for sound card

### ISSUE THREAD

**Issue by exander77** [yu2924/BodeAnalyzer#1]
Hello, I love the tool, I was kinda hard to compile on Linux with projucer and all the libraries, it would really benefit from build structure. Do you plan to develop it more or accept pull requests?

What sound card is best to not influence measurements? I tried some Chinese USB, and it was garbage, but my IcyBox IB-AC527 looks ok, but it drops on low and high frequencies so it is not entirely flat, this is measuring with just a direct cable connecting input to output:
![image](https://github.com/yu2924/BodeAnalyzer/assets/2256039/fc48b280-dba4-4b33-824b-688def84dd46)

Or there could a functionality to record direct cable connection and then compensate for the imperfection when measuring the circuit.

**Comment by exander77** [comment]
This is the noname Chinese card:
![image](https://github.com/yu2924/BodeAnalyzer/assets/2256039/de33eade-e492-4a82-aa61-531b3156ca6c)

**Comment by exander77** [comment]
This is the noname Chinese card from Aliexpress:
![image](https://github.com/yu2924/BodeAnalyzer/assets/2256039/aec3a67f-fbcb-4999-b375-1417098c00bb)

**Comment by exander77** [comment]
I have another one, looks slightly better:
![image](https://github.com/yu2924/BodeAnalyzer/assets/2256039/12c3b4cf-00db-4e3e-b742-544d4c5784c0)

**Comment by yu2924** [comment]
Thank you for your interest in this repository.

Unfortunately, I have no motivation to continue further development at this time. But of course you are welcome to copy or modify the code yourself.

Since this implementation has no calibration function, the error factor of the audio hardware becomes the measurement error directly. Therefore, high-precision hardware is required. Suitable audio interfaces for measurement would be those used by musicians and audio engineers. I'm using the RME Multiface AE audio interface on Windows, which is good enough for measurements, but a bit expensive.

If the measurement results show flat amplitude but phase shift as the frequency increases, there may be some error in latency.
